version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: books_my_postgres_gh
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - books_net_gh

networks:
  books_net_gh:
    driver: bridge

volumes:
  postgres_data:
